- name: Build Docker Image
  hosts: dockerservers
  gather_facts: false
  remote_user: root

  tasks:
    - name: Building Docker Image
      docker_image:
        name: team33-neogym:latest    # ชื่อของ Docker image
        source: build
        build:
          path: ~/team33-neogym       # path ที่เก็บไฟล์ source code
        state: present
        force_source: true
