- name: Deploy Docker Container
  hosts: dockerservers
  gather_facts: false
  remote_user: root

  tasks:
    - name: Creating the Container
      docker_container:
        name: 66022703-neogym-container   # ชื่อของ Docker container
        image: 66022703-neogym:latest     # ชื่อของ Docker image
        ports:
          - "80:80"                     # Mapping พอร์ต: พอร์ต 33 (host) -> พอร์ต 80 (container)
        state: started                  # ให้ container ทำงานทันทีหลังจากสร้างเสร็จ
        restart: true                   # ถ้า container หยุดทำงาน จะให้เริ่มทำงานใหม่อัตโนมัติ
